# Generated by Django 2.2.9 on 2020-07-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='demo'),
        ),
    ]
