# Generated by Django 2.2.9 on 2020-07-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_demo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
